services:
  app:
    image: template:0.0.3
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
      - ENVIRONMENT=LOCAL
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
